In [0]:
df = spark.read.format("csv").option("header", "true").load("dbfs:/FileStore/shared_uploads/nanivasireddy99@gmail.com/emp.csv")
display(df)

EMPNO,ENAME,JOB,HIREDATE,Dept No
1,A,CLERK,17-12-1980,10
2,B,SALESMAN,20-02-1981,20
3,C,MANAGER,22-02-1981,30
4,D,ANALYST,21-09-1981,40
5,E,CLERK,17-12-1980,10
6,F,SALESMAN,20-02-1981,20
7,G,MANAGER,22-02-1981,30
8,H,ANALYST,21-09-1981,40
9,I,CLERK,17-12-1980,10
10,J,SALESMAN,20-02-1981,20
11,K,MANAGER,22-02-1981,30
12,L,ANALYST,21-09-1981,40

In [0]:
df.sort(df['ename'].desc()).show()

+-----+-----+--------+----------+-------+
|EMPNO|ENAME|     JOB|  HIREDATE|Dept No|
+-----+-----+--------+----------+-------+
|   12|    L| ANALYST|21-09-1981|     40|
|   11|    K| MANAGER|22-02-1981|     30|
|   10|    J|SALESMAN|20-02-1981|     20|
|    9|    I|   CLERK|17-12-1980|     10|
|    8|    H| ANALYST|21-09-1981|     40|
|    7|    G| MANAGER|22-02-1981|     30|
|    6|    F|SALESMAN|20-02-1981|     20|
|    5|    E|   CLERK|17-12-1980|     10|
|    4|    D| ANALYST|21-09-1981|     40|
|    3|    C| MANAGER|22-02-1981|     30|
|    2|    B|SALESMAN|20-02-1981|     20|
|    1|    A|   CLERK|17-12-1980|     10|
+-----+-----+--------+----------+-------+

In [0]:
df.sort(df['ename'].desc()).show()

+-----+-----+--------+----------+-------+
|EMPNO|ENAME|     JOB|  HIREDATE|Dept No|
+-----+-----+--------+----------+-------+
|   12|    L| ANALYST|21-09-1981|     40|
|   11|    K| MANAGER|22-02-1981|     30|
|   10|    J|SALESMAN|20-02-1981|     20|
|    9|    I|   CLERK|17-12-1980|     10|
|    8|    H| ANALYST|21-09-1981|     40|
|    7|    G| MANAGER|22-02-1981|     30|
|    6|    F|SALESMAN|20-02-1981|     20|
|    5|    E|   CLERK|17-12-1980|     10|
|    4|    D| ANALYST|21-09-1981|     40|
|    3|    C| MANAGER|22-02-1981|     30|
|    2|    B|SALESMAN|20-02-1981|     20|
|    1|    A|   CLERK|17-12-1980|     10|
+-----+-----+--------+----------+-------+

In [0]:
df.sort(df['Dept No'].asc()).show()

+-----+-----+--------+----------+-------+
|EMPNO|ENAME|     JOB|  HIREDATE|Dept No|
+-----+-----+--------+----------+-------+
|    1|    A|   CLERK|17-12-1980|     10|
|    5|    E|   CLERK|17-12-1980|     10|
|    9|    I|   CLERK|17-12-1980|     10|
|    2|    B|SALESMAN|20-02-1981|     20|
|    6|    F|SALESMAN|20-02-1981|     20|
|   10|    J|SALESMAN|20-02-1981|     20|
|    3|    C| MANAGER|22-02-1981|     30|
|    7|    G| MANAGER|22-02-1981|     30|
|   11|    K| MANAGER|22-02-1981|     30|
|    4|    D| ANALYST|21-09-1981|     40|
|    8|    H| ANALYST|21-09-1981|     40|
|   12|    L| ANALYST|21-09-1981|     40|
+-----+-----+--------+----------+-------+

In [0]:
from pyspark.sql.functions import *
df.orderBy(col('Dept No')).show()

+-----+-----+--------+----------+-------+
|EMPNO|ENAME|     JOB|  HIREDATE|Dept No|
+-----+-----+--------+----------+-------+
|    1|    A|   CLERK|17-12-1980|     10|
|    5|    E|   CLERK|17-12-1980|     10|
|    9|    I|   CLERK|17-12-1980|     10|
|    2|    B|SALESMAN|20-02-1981|     20|
|    6|    F|SALESMAN|20-02-1981|     20|
|   10|    J|SALESMAN|20-02-1981|     20|
|    3|    C| MANAGER|22-02-1981|     30|
|    7|    G| MANAGER|22-02-1981|     30|
|   11|    K| MANAGER|22-02-1981|     30|
|    4|    D| ANALYST|21-09-1981|     40|
|    8|    H| ANALYST|21-09-1981|     40|
|   12|    L| ANALYST|21-09-1981|     40|
+-----+-----+--------+----------+-------+

In [0]:
df.orderBy('Dept No').show()

+-----+-----+--------+----------+-------+
|EMPNO|ENAME|     JOB|  HIREDATE|Dept No|
+-----+-----+--------+----------+-------+
|    1|    A|   CLERK|17-12-1980|     10|
|    5|    E|   CLERK|17-12-1980|     10|
|    9|    I|   CLERK|17-12-1980|     10|
|    2|    B|SALESMAN|20-02-1981|     20|
|    6|    F|SALESMAN|20-02-1981|     20|
|   10|    J|SALESMAN|20-02-1981|     20|
|    3|    C| MANAGER|22-02-1981|     30|
|    7|    G| MANAGER|22-02-1981|     30|
|   11|    K| MANAGER|22-02-1981|     30|
|    4|    D| ANALYST|21-09-1981|     40|
|    8|    H| ANALYST|21-09-1981|     40|
|   12|    L| ANALYST|21-09-1981|     40|
+-----+-----+--------+----------+-------+